name: Lint and Type Check

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  lint-typescript:
    name: Lint TypeScript/JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ESLint
        run: pnpm lint

      - name: Run TypeScript type check
        run: pnpm typecheck

  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install Python dependencies
        working-directory: packages/graphql
        run: uv sync --all-extras

      - name: Run flake8
        working-directory: packages/graphql
        run: uv run flake8 src/ tests/

      - name: Run mypy
        working-directory: packages/graphql
        run: uv run mypy src/

      - name: Check black formatting
        working-directory: packages/graphql
        run: uv run black --check src/ tests/

      - name: Check isort formatting
        working-directory: packages/graphql
        run: uv run isort --check-only src/ tests/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [lint-typescript, lint-python]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: "latest"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.6

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Python dependencies
        working-directory: packages/graphql
        run: uv sync --all-extras

      - name: Run tests
        run: pnpm test